linters:
  enable:
    - bodyclose
    - contextcheck
    - gofmt
    - goimports
    - misspell
    - nilerr
linters-settings:
  errcheck:
    # exclude the following functions since we don't generally
    # need to be concerned with the returned errors
    exclude-functions:
      - encoding/binary.Read
      - (*os.File).Seek
      - (*bufio.Writer).WriteString
      - (*github.com/spf13/pflag.FlagSet).Set
      - (*github.com/jmorganca/ollama/llm.readSeekOffset).Seek
